// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToImplementation
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageString = "2db123d5-dbea-424e-9eef-2a72929f10e6";
        public const string guidToolsMenuGroupString = "753d38b3-3066-4a29-a3f0-d9c8f943d5a7";
        public const string guidEditorContextMenuGroupString = "dda55e00-e6c2-489a-916b-3be66781cf7c";
        public const string guidImagesString = "2eb7d4c5-5562-4f7c-ab7b-8fb0c5d9bca9";
        public static Guid guidVSPackage = new Guid(guidVSPackageString);
        public static Guid guidToolsMenuGroup = new Guid(guidToolsMenuGroupString);
        public static Guid guidEditorContextMenuGroup = new Guid(guidEditorContextMenuGroupString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolsMenuGroup = 0x1020;
        public const int EditorContextMenuGroup = 0x1020;
        public const int GoToImplementationCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
